const MUSICAL_ALPHABET = ["C", "D", "E", "F", "G", "A", "B"]
const PITCHES = ["#", "b"]
const NOTES_COUNT = MUSICAL_ALPHABET.length

const ALLOWED_PITCH_SYMBOLS = PITCHES.join("").toLocaleLowerCase() + PITCHES.join("").toUpperCase()
const ALLOWED_NOTE_SYMBOLS = MUSICAL_ALPHABET.join("").toUpperCase() + MUSICAL_ALPHABET.join("").toLocaleLowerCase()
const ALLOWED_MUSIC_SYMBOLS = ALLOWED_NOTE_SYMBOLS + ALLOWED_NOTE_SYMBOLS

export {MUSICAL_ALPHABET, PITCHES, NOTES_COUNT, ALLOWED_PITCH_SYMBOLS, ALLOWED_NOTE_SYMBOLS, ALLOWED_MUSIC_SYMBOLS}
