const NOTE_NAMES = ["C", "D", "E", "F", "G", "A", "B"]
const PITCHES = ["#", "b"]
const NOTES_COUNT = NOTE_NAMES.length

const ALLOWED_PITCH_SYMBOLS = PITCHES.join("").toLocaleLowerCase() + PITCHES.join("").toUpperCase()
const ALLOWED_NOTE_SYMBOLS = NOTE_NAMES.join("").toUpperCase() + NOTE_NAMES.join("").toLocaleLowerCase()
const ALLOWED_MUSIC_SYMBOLS = ALLOWED_NOTE_SYMBOLS + ALLOWED_NOTE_SYMBOLS

export {NOTE_NAMES, PITCHES, NOTES_COUNT, ALLOWED_PITCH_SYMBOLS, ALLOWED_NOTE_SYMBOLS, ALLOWED_MUSIC_SYMBOLS}
