const CHROMATIC_SCALE = ["C", "D", "E", "F", "G", "A", "B"]
const PITCHES = ["#", "b"]
const NOTES_COUNT = CHROMATIC_SCALE.length

const ALLOWED_PITCH_SYMBOLS = PITCHES.join("").toLocaleLowerCase() + PITCHES.join("").toUpperCase()
const ALLOWED_NOTE_SYMBOLS = CHROMATIC_SCALE.join("").toUpperCase() + CHROMATIC_SCALE.join("").toLocaleLowerCase()
const ALLOWED_MUSIC_SYMBOLS = ALLOWED_NOTE_SYMBOLS + ALLOWED_NOTE_SYMBOLS

export {CHROMATIC_SCALE, PITCHES, NOTES_COUNT, ALLOWED_PITCH_SYMBOLS, ALLOWED_NOTE_SYMBOLS, ALLOWED_MUSIC_SYMBOLS}
