# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        make install-dev
    - name: Lint with black
      run: |
        make test-black
    - name: Lint with flake8
      run: |
        make test-flake8
    - name: Lint with isort
      run: |
        make test-isort
    - name: Test with pytest
      run: |
        make test-pytest
